version: "2"
services:
  json-server:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 8080 -w db.json
    ports:
      - "8080:8080"
    volumes:
      - ./json-server:/data
      - ./src:/data/public
    restart: always
