version: "2"
services:
  json-server:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 8080 -w db.json
    ports:
      - "8080:8080"
    volumes:
      - ./json-server:/data
      - ./src:/data/public
    restart: always

  node:
    image: "node:latest"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./squiggly-server:/home/node/app
    ports:
      - "8081:8081"
    tty: yes
    #command: "npm start"
    #restart: always
